import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import PanelComponent, {PanelAlignment} from "@/components/panelComponent/PanelComponent";
import Button from "@/components/button/Button";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout() {
    return (
        <html lang="en" className="h-screen">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}>
        {/*<FileViewerApp />*/}
        {/* <AnimatedButtonApp />*/}
        {/*<FunctionContainer />*/}
        <PanelComponent alignment={PanelAlignment.LEFT}>
            <div className="flex flex-col p-4">
                <Button>Foo</Button>
                <Button>Bar</Button>
            </div>
        </PanelComponent>
        <PanelComponent alignment={PanelAlignment.RIGHT} emptyView={EmptyFunctionEditorView()}>
            {/*<div>Foo</div>*/}
        </PanelComponent>
        </body>
        </html>
    );
}

function EmptyFunctionEditorView() {
    return <div className="flex flex-row">
        <div>Select or</div>
        <Button inline={true}>create</Button>
        <div>a function</div>
    </div>
}
