import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPicker from "../components/HeaderPicker";
import HeaderTitle from "../components/HeaderTitle";
import { TreeProvider } from "../context/FileTreeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}>
        <TreeProvider>
          <nav className="navbar bg-base-200 border-b border-base-300">
            <div className="flex-1">
              <HeaderTitle />
            </div>
            <div className="flex-none">
              <HeaderPicker />
            </div>
          </nav>
          <div className="flex-1 min-h-0">{children}</div>
        </TreeProvider>
      </body>
    </html>
  );
}
