import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <nav className="navbar bg-base-200 border-b border-base-300">
          <div className="flex-1">
            <span className="text-lg font-semibold px-2">Playground</span>
          </div>
          <div className="flex-none"></div>
        </nav>
        <div className="flex-1 min-h-0">{children}</div>
      </body>
    </html>
  );
}
